# Generated by Django 5.1.4 on 2024-12-05 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0002_event_is_started_alter_task_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_manager.event', verbose_name='Событие')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_manager.team', verbose_name='Команда')),
            ],
        ),
    ]
