# Generated by Django 5.1.4 on 2024-12-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0003_teaminevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskanswer',
            name='mark',
            field=models.PositiveIntegerField(default=0, verbose_name='Баллы за ответ'),
        ),
    ]
