# Generated by Django 5.1.4 on 2024-12-06 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0004_alter_taskanswer_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskanswer',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskanswer',
            name='team',
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, verbose_name='Название задачи')),
                ('max_scroe', models.PositiveIntegerField(verbose_name='Максимальный балл')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_manager.event', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskAnswer',
        ),
    ]
