# Generated by Django 5.1.4 on 2024-12-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0005_remove_taskanswer_task_remove_taskanswer_team_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Название задачи'),
        ),
    ]
