# Generated by Django 5.1.4 on 2024-12-06 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0006_alter_step_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField()),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_manager.step')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_manager.team')),
            ],
        ),
    ]
