# Generated by Django 5.1.4 on 2024-12-06 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0007_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='teaminevent',
            name='event',
        ),
        migrations.RemoveField(
            model_name='teaminevent',
            name='team',
        ),
        migrations.RemoveField(
            model_name='userinteam',
            name='team',
        ),
        migrations.RemoveField(
            model_name='userinteam',
            name='user',
        ),
        migrations.AddField(
            model_name='team',
            name='event',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='event_manager.event', verbose_name='Мероприятие'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='TeamInEvent',
        ),
        migrations.DeleteModel(
            name='UserInTeam',
        ),
    ]
