# Generated by Django 5.1.4 on 2024-12-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0008_remove_customuser_role_remove_teaminevent_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admin_access',
            field=models.BooleanField(default=False),
        ),
    ]
